name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./testes-automatizados-cypress-basico
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          working-directory: ./testes-automatizados-cypress-basico
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./testes-automatizados-cypress-basico
