name: End-to-end tests 🧪
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          working-directory: ./testes-automatizados-cypress-basico
